finally i was able to push my repo in github after error
task completed by local